merchex/merchex/urls.py
from django.contrib import admin
from django.urls import path
from listings import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bands/', views.band_list, name='band-list'),
    path('bands/<int:band_id>/', views.band_detail, name='band-detail'),
    path('bands/add/', views.band_create, name='band-create'),
    path('bands/<int:band_id>/change/', views.band_update, name='band-update'),
    path('bands/<int:band_id>/delete/', views.band_delete, name='band-delete'),
    path('about-us/', views.about, name='about'),
    path('listings/', views.listings, name='goody-list'),
    path('listing/<int:goody_id>/', views.goody_detail, name='goody-detail'),
    path('listings/add/', views.goody_create, name='goody-create'),
    path('listings/<int:goody_id>/change/', views.goody_update,
         name='goody-update'),
    path('listings/<int:goody_id>/delete/', views.goody_delete,
         name='goody-delete'),
    path('contact-us/', views.contact, name='contact'),
    path('email-sent/', views.email_sent, name='email-sent'),
]

merchex/listings/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator


class Band(models.Model):

    class Genre(models.TextChoices):
        HIP_HOP = "HH"
        SYNTH_POP = "SP"
        ALTERNATIVE_ROCK = "AR"

    name = models.fields.CharField(max_length=100)
    genre = models.fields.CharField(choices=Genre.choices, max_length=5)
    biography = models.fields.CharField(max_length=1000)
    year_formed = models.fields.IntegerField(
        validators=[MinValueValidator(1900), MaxValueValidator(2021)]
    )
    active = models.fields.BooleanField(default=True)
    official_homepage = models.fields.URLField(null=True, blank=True)

    def __str__(self):
        return f'{self.name}'


class Goodies(models.Model):

    class Type(models.TextChoices):
        Records = "REC"
        Clothing = "CLTH"
        Posters = "PSTR"
        Miscellaneous = "MSLS"

    title = models.fields.CharField(max_length=100)
    description = models.fields.CharField(max_length=1000)
    sold = models.fields.BooleanField(default=False)
    year = models.fields.IntegerField(null=True, blank=True)
    type = models.fields.CharField(choices=Type.choices, max_length=8)

    band = models.ForeignKey(Band, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return f"{self.title}"

merchex/listings/forms.py
from django import forms
from listings.models import Band, Goodies


class ContactUsForm(forms.Form):
    name = forms.CharField(required=False)
    email = forms.EmailField()
    message = forms.CharField(max_length=1000)


class BandForm(forms.ModelForm):
    class Meta:
        model = Band
        # fields = '__all__'
        exclude = ('active', 'official_homepage')


class GoodiesForm(forms.ModelForm):
    class Meta:
        model = Goodies
        fields = '__all__'

merchex/listings/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.core.mail import send_mail
from listings.models import Band, Goodies
from listings.forms import BandForm, GoodiesForm, ContactUsForm


def band_list(request):
    bands = Band.objects.all()
    return render(request, 'listings/band_list.html', {'bands': bands})


def band_detail(request, band_id):
    band = Band.objects.get(id=band_id)
    return render(request, 'listings/band_detail.html', {'band': band})


def band_create(request):
    if request.method == 'POST':
        form = BandForm(request.POST)
        if form.is_valid():
            band = form.save()
            return redirect('band-detail', band.id)
    else:
        form = BandForm()

    return render(request, 'listings/band_create.html', {'form': form})


def band_update(request, band_id):
    band = Band.objects.get(id=band_id)

    if request.method == 'POST':
        form = BandForm(request.POST, instance=band)
        if form.is_valid():
            form.save()
            return redirect('band-detail', band.id)
    else:
        form = BandForm(instance=band)

    return render(request, 'listings/band_update.html', {'form': form})


def band_delete(request, band_id):
    band = Band.objects.get(id=band_id)

    if request.method == 'POST':
        band.delete()
        return redirect('band-list')

    return render(request, 'listings/band_delete.html', {'band': band})


def about(request):
    return render(request, 'listings/about.html')


def listings(request):
    goodies = Goodies.objects.all()
    return render(request, 'listings/listings.html', {'goodies': goodies})


def goody_detail(request, goody_id):
    goody = Goodies.objects.get(id=goody_id)
    return render(request, 'listings/goody_detail.html', {'goody': goody})


def goody_create(request):
    if request.method == 'POST':
        form = GoodiesForm(request.POST)
        if form.is_valid():
            goody = form.save()
            return redirect('goody-detail', goody.id)
    else:
        form = GoodiesForm()

    return render(request, 'listings/goody_create.html', {'form': form})


def goody_update(request, goody_id):
    goody = Goodies.objects.get(id=goody_id)

    if request.method == 'POST':
        form = GoodiesForm(request.POST, instance=goody)
        if form.is_valid():
            form.save()
            return redirect('goody-detail', goody.id)
    else:
        form = GoodiesForm(instance=goody)

    return render(request, 'listings/goody_update.html', {'form': form})


def goody_delete(request, goody_id):
    goody = Goodies.objects.get(id=goody_id)

    if request.method == 'POST':
        goody.delete()
        return redirect('goody-list')

    return render(request, 'listings/goody_delete.html', {'goody': goody})


def email_sent(request):
    return render(request, 'listings/email_sent.html')


def contact(request):
    # l envoie d un vrai mail se ferai grace
    # a la configuration d un serveur SMTP

    if request.method == 'POST':
        form = ContactUsForm(request.POST)

        if form.is_valid():
            send_mail(subject=f"Message from "
                              f"{form.cleaned_data['name'] or 'anonyme'} "
                              f"via MerchEx Contact Us form",
                      message=form.cleaned_data["message"],
                      from_email=form.cleaned_data["email"],
                      recipient_list=["admin@merchex.xyz"]
                      )
            return redirect('email-sent')

    else:
        form = ContactUsForm()

    return render(request, 'listings/contact.html', {'form': form})

merchex/listings/templates/listings/about.html
{% extends 'listings/base.html' %}

{% block content %}

	<h1>A propos</h1>
	<p>Nous adorons merch !</p>

{% endblock %}

merchex/listings/templates/listings/band_create.html
{% extends 'listings/base.html' %}

{% block content %}

	<h1>Création d'un groupe</h1>

	<form action="" method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Envoyer">
	</form>

{% endblock %}

merchex/listings/templates/listings/band_delete.html
{% extends 'listings/base.html' %}

{% block content %}

	<h1>Suppression du groupe</h1>

	<p>Êtes-vous sûr de vouloir supprimer le groupe : {{ band.name }} ?</p>

	<form action="" method="post">
		{% csrf_token %}
		<input type="submit" value="Supprimer">
	</form>

{% endblock %}

merchex/listings/templates/listings/band_detail.html
{% extends 'listings/base.html' %}

{% block content %}

<h2>{{ band.name }}</h2>

<ul>
	<li>Genre : {{ band.get_genre_display }}</li>
	<li>Année de formation : {{ band.year_formed }}</li>
	<li>Actif : {{ band.active|yesno }}</li>
	{% if band.official_homepage %}
	<li><a href="{{ band.official_homepage }}">{{ band.official_homepage }}</a></li>
	{% endif %}
</ul>

<p>{{ band.biography }}</p>

<a href="{% url 'band-update' band.id %}">Modifier ce groupe</a>

<a href="{% url 'band-delete' band.id %}">Supprimer ce groupe</a>

<a href="{% url 'band-list' %}">Retour à tous les groupes</a>

{% endblock %}

merchex/listings/templates/listings/band_list.html
{% extends 'listings/base.html' %}

{% block content %}

	<h1>Groupes</h1>

	<a href="{% url 'band-create' %}">Créer un nouveau groupe</a>

	<ul>
		{% for band in bands %}
		<li>
			<a href="{% url 'band-detail' band.id %}">{{ band.name }}</a>
			 - <a href="{% url 'band-update' band.id %}">[Modifier]</a>
			 - <a href="{% url 'band-delete' band.id %}">[Supprimer]</a>
		</li>
		{% endfor %}
	</ul>

{% endblock %}

merchex/listings/templates/listings/band_update.html
{% extends 'listings/base.html' %}

{% block content %}

	<h1>Changement du groupe</h1>

	<form action="" method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Envoyer">
	</form>

{% endblock %}

merchex/listings/templates/listings/base.html
<!DOCTYPE html>

{% load static %}

<html lang="fr">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Merchex</title>
	<link rel="stylesheet" href="{% static 'listings/styles.css' %}" >

</head>
<body>

	<nav>
		<ul>
			<li><a href="{% url 'band-list' %}">Groupes</a></li>
			<li><a href="{% url 'goody-list' %}">Goodies</a></li>
			<li><a href="{% url 'contact' %}">Contact</a></li>
			<li><a href="{% url 'about' %}">A propos</a></li>
		</ul>
	</nav>

	{% block content %}{% endblock %}

</body>
</html>

merchex/listings/templates/listings/email_sent.html
{% extends 'listings/base.html' %}

{% block content %}

	<p>Votre message a bien été envoyé, nous allons traiter
		votre demande dans les plus brefs délais</p>

{% endblock %}

merchex/listings/templates/listings/goody_create.html
{% extends 'listings/base.html' %}

{% block content %}

	<h1>Création d'un goody</h1>

	<form action="" method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Envoyer">
	</form>

{% endblock %}

merchex/listings/templates/listings/goody_delete.html
{% extends 'listings/base.html' %}

{% block content %}

	<h1>Suppression du goody</h1>

	<p>Êtes-vous sûr de vouloir supprimer le goody : {{ goody.title }} ?</p>

	<form action="" method="post">
		{% csrf_token %}
		<input type="submit" value="Supprimer">
	</form>

{% endblock %}

merchex/listings/templates/listings/goody_detail.html
{% extends 'listings/base.html' %}

{% block content %}

<h2>{{ goody.title }}</h2>

<ul>
	<li>Type : {{ goody.get_type_display }}</li>
	<li>Vendu : {{ goody.sold|yesno }}</li>
	<li>Année de production : {{ goody.year }}</li>
	{% if goody.band %}
	<li>Groupe relatif : <a href="{% url 'band-detail' goody.band.id %}">{{ goody.band }}</a></li>
	{% endif %}
</ul>

<p>{{ goody.description }}</p>

<a href="{% url 'goody-update' goody.id %}">Modifier ce goody</a>

<a href="{% url 'goody-delete' goody.id %}">Supprimer ce goody</a>

<a href="{% url 'goody-list' %}">Retour aux goodies</a>

{% endblock %}

merchex/listings/templates/listings/goody_update.html
{% extends 'listings/base.html' %}

{% block content %}

	<h1>Changement du goody</h1>

	<form action="" method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Envoyer">
	</form>

{% endblock %}

merchex/listings/templates/listings/hello.html
{% extends 'listings/base.html' %}

{% block content %}

	<h1>Hello Django!</h1>
	<p>Mes groupes préférés sont :</p>
	<ul>
		{% for band in bands %}
			<li>
				{{ band.name }}
			</li>
		{% endfor %}
	</ul>

{% endblock %}

merchex/listings/templates/listings/listings.html
{% extends 'listings/base.html' %}

{% block content %}

	<h1>Goodies</h1>

	<a href="{% url 'goody-create' %}">Créer un nouveau goody</a>

	<ul>
		{% for goody in goodies %}
			<li>
				<a href="{% url 'goody-detail' goody.id %}">{{ goody.title }}</a>
				 - <a href="{% url 'goody-update' goody.id %}">[Modifier]</a>
				 - <a href="{% url 'goody-delete' goody.id %}">[Supprimer]</a>
			</li>
		{% endfor %}
	</ul>

{% endblock %}